### PR TITLE
Task done

### PR DESCRIPTION
**Pull request by RibhavBansal**
Issue: 32

Commands that you used to complete this issue.

-cd .\GoGit-2.0\
-git log --reverse
-SHA - b1bf24d5046ff5590c03e43b43872c631cb37450
-git checkout b1bf24d5046ff5590c03e43b43872c631cb37450
-git checkout -b initial-branch
-touch info.md
-Edit file info.md
-git add .
-git status
-git commit -m "Tell the Difference"
-git branch --show-current
-git push -u origin initial-branch

### CODE REVIEW

**Comment by RibhavBansal** [comment]
@ABHAY0O7 sir pls review this.

**Comment by ABHAY0O7** [comment]
@RibhavBansal Your answer is still vague, just answer to the point in which case the branch is master and in which main.

**Comment by RibhavBansal** [comment]
Can i get more time Or u are Reassigning this issue?

**Comment by ABHAY0O7** [comment]
> @ABHAY0O7 Can i get more time Or u are Reassigning this issue?

You have only today's day to correct it.

**Comment by RibhavBansal** [comment]
> 
> > @ABHAY0O7 Can i get more time Or u are Reassigning this issue?
> 
> You have only today's day to correct it.
> 
> 

@ABHAY0O7 Sir is this not correct? 

if we add a README file, main branch is default branch
But if we didn't add then master branch is default branch

**Comment by ABHAY0O7** [comment]
@RibhavBansal Whenever free, ping me on discord.

**Comment by RibhavBansal** [comment]
> @RibhavBansal Whenever free, ping me on discord.

Sir i am free now

**Comment by ABHAY0O7** [comment]
Not answered accurately.

**Pull request closed without merging**
