### PR TITLE
added info.md file

### PR DESCRIPTION
**Pull request by bhumika-kalaru**
Issue: 1

Commands that you used to complete this issue.

- git clone
- git status
- git add
- git commit
- got push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Did u clone the repo?

**Comment by bhumika-kalaru** [comment]
yes

**Comment by bhumika-kalaru** [comment]
yes,Forgot to add it...!

**Comment by ABHAY0O7** [comment]
The commands are still incomplete. @bhumika-kalaru 

This time I am allowing, next time write complete and proper commands.

**Pull request merged**
