### PR TITLE
private repo

### PR DESCRIPTION
**Pull request by TheDivineAurora**
Issue: 2

Commands that you used to complete this issue.

-  git add --all
-  git commit -m "personal repo"
-  git push origin
-
-

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
You didn't do the task correctly, reread the task and identify your mistake. @TheDivineAurora

**Comment by TheDivineAurora** [comment]
updated url , do check

**Comment by ABHAY0O7** [comment]
Next time, write complete commands.

**Comment by TheDivineAurora** [comment]
> Next time, write complete commands.

Ok sir

**Pull request merged**
