### PR TITLE
added info.md

### PR DESCRIPTION
**Pull request by Riddhikedia**
Issue: 1

Commands that you used to complete this issue.

-First I created Riddhi Kedia folder in Second Year and added info.md. Then in terminal I used these commands:
-git add .
-git commit -m "Added info.md"
-git push

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Your PR has [this](https://github.com/opencodeiiita/GoGit-2.0/pull/4#issuecomment-1356461819) problem. @Riddhikedia

**Comment by Riddhikedia** [comment]
@ABHAY0O7 Sir i have made a new branch for task2.
Kindly merge pr 40 and pr 56

**Comment by ABHAY0O7** [comment]
@Riddhikedia Please remove the changes of task - 2 from this PR.

**Comment by Riddhikedia** [comment]
@ABHAY0O7 Sir I removed the changes of task-2 from this pr

**Pull request merged**
