### PR TITLE
done task

### PR DESCRIPTION
**Pull request by sushantk1274**
Issue: 1

Forked the repository.
Cloned using the git clone command.
Added the info.md file in the given location.
Added the files to staging area by the command git add .

Committed changes using the command git commit -m "done task"
i have pushed the changes to my remote repository using git push.

### CODE REVIEW

**Comment by sushantk1274** [comment]
also done second task please check commit

**Comment by ABHAY0O7** [comment]
Nyc work @sushantk1274 

Everything is good, except the way of contribution.
- You should solve only one issue in a single PR.
- You should always make a new branch first before doing any contributions to an issue.

Also, you will no get points for task 2 if this PR is merged you have to make another one for that so remove your task-2 changes and make a separate PR for it.

For any help, use discord.

**Comment by sushantk1274** [comment]
> Nyc work @sushantk1274
> 
> Everything is good, except the way of contribution.
> 
> * You should solve only one issue in a single PR.
> * You should always make a new branch first before doing any contributions to an issue.
> 
> Also, you will no get points for task 2 if this PR is merged you have to make another one for that so remove your task-2 changes and make a separate PR for it.
> 
> For any help, use discord.

ok sir but i am unable to make a new pr for task 2 so that i cant make a new pr foir task 2 as only view pull req is showing for that

**Comment by ABHAY0O7** [comment]
> 

Thats why I mentioned 'git branch', with one branch you can only make one open PR at a time, and with multiple you can create multiple open PRs at a time.

**Comment by sushantk1274** [comment]
Respected sir I have created branches and have done both task kindly merge
pr 17 and 18

**Pull request closed without merging**
