### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by bhumi-cka**
Issue: 1

- Forked the repository.
- Initialized git using  ```git init``` in my command line.
- Cloned it on my local system using the ```git clone``` command.
- Added the info.md file in the given location.
- Added the files to staging area by the command ```git add .```
- Committed changes using the command  ```git commit -m "Task 1"```
- Pushed the changes to my remote repository using ```git push -u origin main```
- Created this pull request

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Hey @bhumi-cka 

Nyc work 👏🏽 
Good start, everything is fine except for the second step.
> Initialized git using git init in my command line.
This should not be present there.

I will merge your PR when you will tell me why this is wrong, in this thread.
If you want any help mention it on discord.

**Comment by bhumi-cka** [comment]
```git init``` initializes an empty git repository. There was no need for this as I just had to clone a remote repository.

**Comment by ABHAY0O7** [comment]
> `git init` initializes an empty git repository. There was no need for this as I just had to clone a remote repository.

Still the answer is vague.

**Comment by ABHAY0O7** [comment]
Also since you completed second task too in this PR so now your PR has this [problem](https://github.com/opencodeiiita/GoGit-2.0/pull/4#issuecomment-1356461819) too.

**Comment by bhumi-cka** [comment]
I see. I'll make the changes.
```git clone``` is a combination of ```git init```, ```git remote add```, ```git fetch``` and ```git checkout```. So there is no need to do a ```git init```, as it is already done in ```git clone```.
This is an answer I found on stackoverflow.

**Comment by bhumi-cka** [comment]
So should I fork the repo again and start anew?

**Comment by ABHAY0O7** [comment]
> I see. I'll make the changes. `git clone` is a combination of `git init`, `git remote add`, `git fetch` and `git checkout`. So there is no need to do a `git init`, as it is already done in `git clone`. This is an answer I found on stackoverflow.

Yup, thats the correct answer.


> So should I fork the repo again and start anew?

There are various ways to correct your PR.
- Remove the task 2 changes and push the changes. (best)
- Delete the task 2 commit. (good)
- Reset your main branch with my main and redo tasks.(bad)
- delete the repo and redo task.(worst)

All are accepted, for now.

**Comment by bhumi-cka** [comment]
I have removed the task 2 changes.

**Comment by ABHAY0O7** [comment]
Great work & patience @bhumi-cka 
Indeed a lot of hard work for those little 10 points 😄

But, I hope you learned something and good luck with your journey.

**Pull request merged**
