### PR TITLE
private issue repo

### PR DESCRIPTION
**Pull request by IEC2021103Abhinav**
Issue: 2

Commands that you used to complete this issue.

-At first, I  forked your repo.Then, Clone in my desktop folder by  pasting "git clone  forked repo link" in window terminal.
-I have created a private repo and added you as a colllaborator from settings.
-Then by git add . ,git commit ,and git push ,solved this issue

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
Copy to shi se kar yrr 😮‍💨 @IEC2021103Abhinav 
image

**Comment by IEC2021103Abhinav** [comment]
Sorry sir 
wo name wahi rah gya baaki link wagera khud ka hai

**Comment by ABHAY0O7** [comment]
> Sorry sir wo name wahi rah gya baaki link wagera khud ka hai

Correct it.

**Comment by IEC2021103Abhinav** [comment]
done sir

**Comment by ABHAY0O7** [comment]
@IEC2021103Abhinav your PR has some issues, ping me on #gogit when you are free.

**Comment by IEC2021103Abhinav** [comment]
Yes sir

**Comment by ABHAY0O7** [comment]
Good work @IEC2021103Abhinav 👍🏽

**Pull request merged**
