### PR TITLE
Private Repo Link Added

### PR DESCRIPTION
**Pull request by RayLikesAnime**
added private repo link

Issue: 2

Commands that you used to complete this issue.

-
-
-

### CODE REVIEW

**Comment by ABHAY0O7** [comment]
@RayLikesAnime No commands? 🤔

**Comment by RayLikesAnime** [comment]
ah my bad
git add *
git push
git clone
git commit -m "yahello"

**Comment by ABHAY0O7** [comment]
> ah my bad git add * git push git clone git commit -m "yahello"

The commands used to complete this task you is not the same as you wrote. 😑

**Comment by RayLikesAnime** [comment]
> > ah my bad git add * git push git clone git commit -m "yahello"
> 
> The commands used to complete this task by you are not the same as you wrote. 😑

ah there was some issue cloning the forked repo
and i already made 1 pr for issue 1 and i thought issue 2 was just for freshers
so i just edited the file in github only T-T
please consider  T_T

**Comment by ABHAY0O7** [comment]
> > > ah my bad git add * git push git clone git commit -m "yahello"
> > 
> > 
> > The commands used to complete this task by you are not the same as you wrote. expressionless
> 
> ah there was some issue cloning the forked repo and i already made 1 pr for issue 1 and i thought issue 2 was just for freshers so i just edited the file in github only T-T please consider T_T

If you didn't clone it then why you wrote the commands, you could have told me that I did it only on GitHub, so no commands.

**Pull request closed without merging**
