### PR TITLE
info.md added

### PR DESCRIPTION
**Pull request by RibhavBansal**
Issue: 1

Commands that you used to complete this issue.

-git clone
-touch info.md
-git add --all
-git commit -m "info.md added"
-git status
-git push

### CODE REVIEW

**Comment by RibhavBansal** [comment]
@ABHAY0O7 Please review this once.

**Comment by ABHAY0O7** [comment]
Why you did do task 2 in task 1 PR?

**Comment by ABHAY0O7** [comment]
Your has [this](https://github.com/opencodeiiita/GoGit-2.0/pull/4#issuecomment-1356461819) problem now.

**Comment by ABHAY0O7** [comment]
This time I am allowing changes from GitHub, next time use Git and commands.

**Pull request merged**
